tryber/sd-014-a-project-frontend-online-store

src/App.js, src/pages/ProductList.jsx
pier programming (Dandara, João Marcelo, Gabriella, Kristiano)
=> [Grupo 1] requisito 2

src/App.js, src/pages/Home.js
=> [GRUPO 31] Campo de busca da tela principal

src/App.js, src/components/CartButton.jsx, src/components/HomeButton.jsx, src/pages/Cart.jsx, src/pages/Home.jsx
=> [Requisito 3 - Grupo 2 ]

src/App.js, src/pages/Cart.js, src/pages/Home.js
=> [GRUPO 31] Cria a página do carrinho de compras

package-lock.json, package.json, src/components/Categories.jsx, src/components/Category.jsx, src/components/HomeMessage.jsx, src/components/ProductCard.jsx, src/components/ProductList.jsx, src/pages/Home.jsx
=> [Requisitos 4 e 5] Main Group 2

src/component/Categories.js, src/pages/Home.jsx, src/services/api.js
=> Req 4 feito em grupo

package-lock.json, src/services/api.js
=> Implementadas as funçoes para requisiçoes a api

src/components/Categories.js, src/components/Loading.js, src/pages/Home.js
=> [GRUPO 31] Listar filtros de categoria obtidos da API

src/components/Categories.js, src/components/ProductCard.js, src/pages/Home.js
=> [GRUPO 31] Liste os produtos buscados por termos

package-lock.json, src/services/api.js
**Requisitos Obrigatorios**
**Requisitos Bônus**
**Requisitos Extras**
=> [GRUPO 12] Requisito 01

package-lock.json, src/App.js, src/pages/Home.jsx
Crie uma página de listagem de produtos vazia
=> [GRUPO 12] Requisito 02

src/components/Categories.jsx, src/pages/Main.js
Requisito 4, adiciona as categorias de produtos na tela principal.
=> [Lucas Rimis e Danilo Menezes] - Main Group 29

src/App.js, src/pages/Home.jsx
=> [Grupo 22] Requisito 2

src/App.js, src/components/ProductCard.js, src/pages/ProductDetails.js
=> [Grupo 31]  -  Redirecione para uma tela com a exibição detalhada do um produto clicado

src/components/Product.jsx, src/pages/Main.js
=> [Lucas Rimis e Danilo Menezes] Main Group 29

src/App.js, src/pages/Cart.js, src/pages/Home.js
Crie a página do carrinho de compras
=> [GRUPO 5] Requesito 3

src/components/AddItemToCart.js, src/components/ProductCard.js, src/pages/Cart.js, src/pages/Home.js, src/services/shoppingCartAPI.js, src/styles/Home.css
=> [GRUPO 31] Adicione produtos a partir da tela de listagem de produtos

src/components/Form.js, src/pages/ProductDetails.js
=> [Grupo 31] Adicionar formulário para avaliar e comentar

src/components/ShoppingCartButton.js, src/pages/Home.js, src/pages/ProductDetails.js
=> [GRUPO 31] Adicione um produto ao carrinho a partir de sua tela de exibição detalhada

src/Components/Product.jsx, src/pages/MyCart.jsx, src/pages/ProductDetails.jsx, src/services/cart.js
Adiciona funcionalidade para adicionar itens ao carrinho pela pagina de detalhes do produto
=> [GRUPO 13] Requisito 9

src/Components/Product.jsx, src/pages/MyCart.jsx, src/services/cart.js
Adiciona funcionalidades para adicionar itens ao carrinho e salvá-los em localStorage.
=> [GRUPO 13] Requisito 8

package-lock.json, src/App.js, src/components/ProductDetails.jsx, src/components/Search.jsx, src/services/api.js
=> Main group 15 req 6-7

src/components/Categories.js, src/pages/Search.js
- Adiciona lista de categorias na página principal
=> [GRUPO 05] Requisito 4

src/components/Rotas.jsx, src/pages/Search.jsx, src/pages/ShoppingCart.jsx
***Grupo 26:***
> [Patrik Batista](https://github.com/patrikbatista)
> [Rafael Friederick](https://github.com/rafaelmfried)
> [Silas Oliveira](https://github.com/Armin1-lab)
> [Tiago H. S. Sathler](https://github.com/tiagosathler)
> [Victor Varges](https://github.com/VictorVarges)
> 
***Pull Request:*** 
> Por: Silas Oliveira
> 22/09/21
> Turma 14 - Tribo A - *One4All*
> [FrontEnd Online Store](https://github.com/tryber/sd-014-a-project-frontend-online-store) :convenience_store:
3. [x] 3. [Crie a página do carrinho de compras] (https://github.com/tryber/sd-014-a-project-frontend-online-store/tree/main-group-26#3-crie-a-p%C3%A1gina-do-carrinho-de-compras)
> **PRIORIDADE 1**  - Criar o botão de carrinho de compras na tela principal, de listagem de produtos, e criar uma tela para o carrinho …
=> [ GRUPO 26 ] - Requisitos 3 e 4

src/components/ListaDeCategorias.jsx, src/components/ListaDeProdutos.jsx, src/pages/main.jsx
Funciona na prática, mas não passa no teste
=> Main group 19 requisito 6

src/components/ListaDeCategorias.jsx
=> [Grupo 19] Update ListaDeCategorias.jsx

src/App.js, src/pages/Cart.js, src/pages/Checkout.js
=> [GRUPO 31] Implementa tela para a finalização da compra.

src/components/Categorias.jsx, src/components/Produtos.jsx, src/pages/Search.jsx, src/services/api.js
=> [ GRUPO 26 ] - Requisito 5

src/services/shoppingCartAPI.js
};
---
OBS: o teste só vai passar depois que o requisito 10 for implementado.
=> [GRUPO 31] Limite a quantidade de produtos adicionados ao carrinho

src/components/Categories.jsx, src/components/SearchField.jsx, src/pages/Home.js
-  Selecione uma categoria e mostre somente os produtos daquela categoria
=> [GRUPO 05] Requisito 6

src/components/ProductCard.jsx, src/pages/ProductDetail.jsx
Desenvolvido junto com @pedrobarreto
=> [GRUPO 8] Correções - Requisitos 8 e 9

src/App.js, src/components/ProductsCard.jsx, src/pages/Home.jsx, src/pages/ProductDetails.jsx
Npm OK [ DO 1 AO 7]
Linter OK
Styles OK
=> [GRUPO 12] [Requisito 07]

src/components/ProductInCart.jsx, src/components/ProductsCard.jsx, src/pages/Cart.jsx, src/services/localstorage.js
Adiciona a lógica do requisito 8. Passando nos testes.
=> [GRUPO 12] Requisito 8

src/App.js, src/components/Product.jsx, src/components/ProductDetail.jsx, src/pages/Main.js
Main group 29 requisito 7 (Passa no teste, mas não no lint).
=> [Lucas Rimis] Requisito 7

src/components/AvaliationForm.jsx, src/components/ProductDetails.jsx, src/components/RenderAvaliation.jsx
Faltou ajeitar um erro do lint pra passar
=> Main grup 15 req 11

src/components/CartProduct.jsx, src/components/ProductCard.jsx, src/pages/ProductDetail.jsx, src/pages/ShoppingCart.jsx
_17 de Setembro, 2021_
- [César Meira](https://github.com/CesarMeira)
- [Edson Macedo](https://github.com/edson-mac)
- [Gustavo Dolzan](https://github.com/gugadolzan)
- [Pedro Barreto](https://github.com/pedrobarreto)
- [Thiago Ribas](https://github.com/thiagoRibasMiranda)
---
=> [GRUPO 8] Requisito 10 - Ajustes

src/App.js, src/components/ProductCard.jsx, src/components/ProductList.jsx, src/pages/ProductDetails.jsx
- Redirecione para uma tela com a exibição detalhada ao clicar na exibição resumida de um produto.
Feito em conjunto com @carlamaximo, @jhonathancs e @vixemari ! Valeu pessoal! :raised_hands:
=> [GRUPO 05] Requisito 7

src/components/AddItemToCart.js, src/components/ProductCard.js, src/pages/Cart.js, src/pages/Home.js, src/pages/ProductDetails.js, src/services/shoppingCartAPI.js
'Carlos Barros (?)',
};
---
OBS: conserta reqs 13 e 14.
=> [Grupo 31] No Carrinho, mostrar a lista de produtos, o valor total e manipular sua quantidade.

src/components/Home.jsx, src/components/ProductDetails.jsx, src/components/ProductReviewForm.jsx, src/components/ShoppingCart.jsx, src/services/api.js
Modifica o texto do botão para apenas 'Carrinho', tornando a interface mais intuitiva e adiciona uma tag `textarea` que satisfaz o requisito 11.
=> [GRUPO 6] - Requisito 11

src/components/ProductEvaluation.jsx, src/pages/Home.jsx, src/pages/ProductDetails.jsx, src/pages/ShoppingCart.jsx
---
- [Cristhyane G Araldi](https://github.com/CristhyaneAraldi).
- [Écio Ferraz](https://github.com/ecioferraz).
- [Gabriel Benedetti](https://github.com/Benedetti14).
- [Lys Prestes](https://github.com/lysprestes).
- [Yan Paroni](https://github.com/YanParoni).
---
=> [Main Group 24] simplifying code

src/App.css, src/components/AddToCart.jsx, src/components/CartProduct.jsx, src/components/ListaDeProdutos.jsx, src/components/ProductCard.jsx, src/components/SearchBar.jsx, src/pages/main.jsx, src/pages/shoppingCart.jsx
Funciona na prática, não passa no requisito(data-testid)
=> Main group 19 requisito 8

src/components/ProductCard.jsx, src/components/ShoppingCartIcon.jsx, src/pages/Home.jsx
_17 de Setembro, 2021_
- [César Meira](https://github.com/CesarMeira)
- [Edson Macedo](https://github.com/edson-mac)
- [Gustavo Dolzan](https://github.com/gugadolzan)
- [Pedro Barreto](https://github.com/pedrobarreto)
- [Thiago Ribas](https://github.com/thiagoRibasMiranda)
---
=> [GRUPO 8] Finalização do projeto

src/components/AddReview.jsx, src/components/CartProduct.jsx, src/components/ProductCard.jsx, src/components/ProductsCheckout.jsx, src/components/ShoppingCartIcon.jsx, src/index.css, src/pages/ProductDetail.jsx, src/pages/ShoppingCart.jsx, src/styles/CartProduct.css, src/styles/ProductCard.css, src/styles/ProductDetail.css, src/styles/ShoppingCart.css
_17 de Setembro, 2021_
- [César Meira](https://github.com/CesarMeira)
- [Edson Macedo](https://github.com/edson-mac)
- [Gustavo Dolzan](https://github.com/gugadolzan)
- [Pedro Barreto](https://github.com/pedrobarreto)
- [Thiago Ribas](https://github.com/thiagoRibasMiranda)
---
=> [GRUPO 8] Requisito 15

src/components/ProductDetail.jsx, src/pages/Main.js
=> [Lucas Rimis] Requisito 9

src/components/CartItem.jsx, src/pages/ShoppingCart.jsx
Cumpre o solicitado no projeto, apenas não faz o cálculo dos valores parcial (por itens) e total do carrinho. 
_OBS:_ O requisito pedia um botão "X" para retirar tudo do carrinho, mas o lint deixou passar.
=> [GRUPO 9 ] - Requisito 10 

src/App.js, src/Components/Product.jsx, src/pages/Checkout.jsx, src/pages/Home.jsx, src/pages/MyCart.jsx, src/pages/ProductDetails.jsx, src/services/cart.js
Adiciona pagina de checkout e formuario
=> [GRUPO 13] Requisito 12

src/components/ProductDetail.jsx
=> [Lucas Rimis] Requisito 11

src/components/Cart.jsx, src/components/CartCard.jsx, src/components/DetalhesProduto.jsx, src/components/Home.jsx, src/components/ListaDeProdutos.jsx, src/components/ProductCard.jsx, src/productStyles.css
=> [Main Group] 21 requisito 10
